# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: 2ae06f51-md-taco
  namespace: 2ae06f51
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: tks
